artist: Devin S.G.
legalName: Devin S.G.
title: Devin S.G.
description: Music, engineering, and multimedia from Devin S.G.
url: https://devin.sg
email: devin@devin.sg
icon: ../../assets/ui/logo.svg
avatar: ../../assets/ui/banner.jpeg
logo:
  light: ../../assets/ui/logo.svg
  dark: ../../assets/ui/logo-white.svg
banner:
  image: ../../assets/ui/banner.jpeg
  position: center 27%
  imageSize: 1.6
  credit: "Photo credit: Devin S.G."

# social handles are optional: blank, null, or omitted social handles are ignored
socials:
  soundcloud: devin_sg
  instagram: 0devin.sg
  bluesky: devin.sg
  twitter:
  email: devin@devin.sg
